# Generated by Django 3.2.5 on 2021-07-06 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='end_time',
            new_name='data_fim',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='start_time',
            new_name='data_inicio',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='description',
            new_name='resumo',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='titulo',
        ),
    ]
